client_config_backend: file
client_config_file: client_secrets.json
client_config:
  client_id: 573878519851-f0m5efvi8lbilcamneu09qpqfvfg6th1.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: saved_credentials.json

get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.install